/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pedro.projeto.telas;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import pedro.projeto.bancodedados.DatabaseConnection;
import pedro.projeto.bancodedados.JDBCAlunos;
import pedro.projeto.modelo.Student;

/**
 *
 * @author Pedro Peixoto Viana de Oliveira
 */
public class ListarAlunos extends javax.swing.JFrame {

    public ListarAlunos() {
        initComponents();
        preencharTabela();
        TableColumnModel columnModel = tabela.getColumnModel();
        TableColumn coluna1 = columnModel.getColumn(0);
        coluna1.setPreferredWidth(50);
        TableColumn coluna2 = columnModel.getColumn(1);
        coluna2.setPreferredWidth(150);
        TableColumn coluna3 = columnModel.getColumn(2);
        coluna3.setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        tabelaScroll = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        tabelaOpcoesBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Listar alunos");

        painelPrincipal.setBackground(new java.awt.Color(0, 20, 66));

        tituloLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Tabela com os alunos");

        tabela.setBackground(new java.awt.Color(204, 204, 255));
        tabela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matrícula", "Nome", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela.setGridColor(new java.awt.Color(0, 0, 0));
        tabela.setSelectionBackground(new java.awt.Color(153, 153, 255));
        tabela.setShowGrid(true);
        tabela.setShowHorizontalLines(true);
        tabelaScroll.setViewportView(tabela);
        if (tabela.getColumnModel().getColumnCount() > 0) {
            tabela.getColumnModel().getColumn(0).setResizable(false);
            tabela.getColumnModel().getColumn(1).setResizable(false);
            tabela.getColumnModel().getColumn(2).setResizable(false);
        }

        tabelaOpcoesBotao.setBackground(new java.awt.Color(7, 84, 83));
        tabelaOpcoesBotao.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabelaOpcoesBotao.setForeground(new java.awt.Color(255, 255, 255));
        tabelaOpcoesBotao.setText("Tabela de opções");
        tabelaOpcoesBotao.setBorder(null);
        tabelaOpcoesBotao.setBorderPainted(false);
        tabelaOpcoesBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabelaOpcoesBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloLabel)
                    .addComponent(tabelaOpcoesBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabelaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(tituloLabel)
                .addGap(30, 30, 30)
                .addComponent(tabelaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabelaOpcoesBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(665, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaOpcoesBotaoActionPerformed(java.awt.event.ActionEvent evt) {
        Opcoes tela = new Opcoes();
        this.dispose();
        tela.setVisible(true);
    }

    // Zera a tabela e busca todos os novos dados no banco de dados e preenche a tabela
    private void preencharTabela() {
        try {
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.setNumRows(0);
        
            DatabaseConnection connection = new DatabaseConnection();
            JDBCAlunos jdbc = new JDBCAlunos(connection.connectionOpen());
        
            ArrayList<Student> alunos = jdbc.listStudents();
            for (int i = 0; i < alunos.size(); i++) {
                Student aluno = alunos.get(i);

                Object[] linha = {aluno.getMatricula(), aluno.getNome(), aluno.getCurso()};
                modelo.addRow(linha);
            }
            connection.connectionClose();
        } catch (SQLException se) {
            se.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTable tabela;
    private javax.swing.JButton tabelaOpcoesBotao;
    private javax.swing.JScrollPane tabelaScroll;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

}
